### ISSUE TITLE
Bank Transfers update and delete support in Xero API

### ISSUE THREAD

**Issue by dominoFire** [XeroAPI/xero-python#167]
The Xero API supports creating and getting Bank Transfers through the API

![image](https://github.com/user-attachments/assets/8469a1a3-98fe-4403-8b23-ea9144522f38)

It would be nice to have the ability to update and delete Bank Transfers through the API

**Comment by Sallyhornet** [comment]
As this is a feature request of the API rather than SDK specific, please can you add your suggestion to our UserVoice site found in the link below, so our Developer Community can show their support for your idea and to receive updates on the request.


Xero UserVoice: [Xero Accounting API](https://xero.uservoice.com/forums/5528-xero-accounting-api)
